### ISSUE TITLE
自由にテストに使える API アカウントの共有（必要なら作成）

### ISSUE THREAD

**Issue by tanigami** [w-takumi/yahoo-shopping-jp-php#3]
@w-takumi/developers 

いつでもトークン更新したりしてもどこにもまったく影響の無い開発専用アカウントを用意しましょう。すでにあるものが使えるならその情報を、作成の必要あれば作成の上、共有してください。

@t-muraguchi さん、こちらやりませんか？（キツければ誰かに Assignee ふりなおしてください）

いったん証明書のことは置いといてやりましょう（早くトークンが切れる方が開発アーリーステージはありがたい）。

**Comment by yfhub** [comment]
@w-takumi/developers API利用回数制限の解除申請はしていませんが、とりあえず作成したのでお知らせします。

> アプリケーションID:
> dj0zaiZpPUxFMlA5RHE3aUw3RyZzPWNvbnN1bWVyc2VjcmV0Jng9ZDA-
> シークレット:
> 3d945db2484a59a1ccb8f6d61eb71324265ebd03
